---
- name: Install Nginx
  hosts: lighthouse
  handlers:
    - name: Start-nginx
      become: true
      ansible.builtin.command: nginx
      tags: nginx
    - name: Reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
      tags: nginx
  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
      tags: nginx
    - name: NGINX | Install NGINX
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Start-nginx
      ignore_errors: "{{ ansible_check_mode }}"
      tags: nginx
    - name: NGINX | Create file for lighthouse config
      become: true
      ansible.builtin.file:
        path: /etc/nginx/conf.d/lighthouse.conf
        state: touch
        mode: "0644"
      tags: nginx
    - name: NGINX | Create general config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Reload-nginx
      tags: nginx
- name: Install LightHouse
  hosts: lighthouse
  
  roles:
    - lighthouse-role
    
  

- name: Install Clickhouse
  hosts: clickhouse
  
  roles:
    - clickhouse

- name: Install and config Vector
  hosts: vector
  
  roles:
    - vector-role
    